### PR TITLE
支持了数据库，shell，多线程，面试宝典，剑指offer

### PR DESCRIPTION
**Pull request by libaoxi**
仓促修改的，不求合并，只希望有需要的可以自己取用，官方早点支持。

### CODE REVIEW

**Comment by HelloC** [comment]
@libaoxi 

能否搞个提交 把数据库，shell，多线程，面试宝典，剑指offer 分开的 ？

**Comment by libaoxi** [comment]
@HelloC 可以，代码量会比较大，等我完成了at你

**Comment by libaoxi** [comment]
@HelloC 好了

**Comment by libaoxi** [comment]
@silence 好了

**Comment by libaoxi** [comment]
@cyh-ustc You can search leetcode on vscode marketplace, I have  published it. Author is libaoxi

**Comment by LesterChang0987** [comment]
> @cyh-ustc You can search leetcode on vscode marketplace, I have published it. Author is libaoxi

hi,thank you publish it.but i cant search leetcode by libaoxi on vscode marketplace,so how can i usr this project

**Pull request closed without merging**
